### ISSUE TITLE
[SUGGESTION] Consider moving this to its own repo

### ISSUE THREAD

**Issue by YPCrumble** [xelixdev/django-pgviews-redux#21]
Thanks for maintaining this fork! I was searching for Django wrappers for Views and only found this maintained repo after an exhaustive search; I had found the base fork a long while before.

As that base is no longer maintained, I suspect if you make this repo its own new repo it will more easily show up in search results.

**Comment by mikicz** [comment]
I've now done this, also renamed it to match the name on PyPI - hopefully that should help
