### ISSUE TITLE
Add support for psycopg3

### ISSUE THREAD

**Issue by hugorodgerbrown** [xelixdev/django-pgviews-redux#24]
The latest minor version of Django (4.2) support psycopg3 (installed as just psycopg). There is currently a hard-coded import of v2 of this library which is prevent us from upgrading.

I will submit a PR.

**Comment by hugorodgerbrown** [comment]
PR submitted - #25

**Comment by mikicz** [comment]
Thanks! Will release soon

**Comment by mikicz** [comment]
0.9.2 with the fix is on PyPI

**Comment by hugorodgerbrown** [comment]
Thanks for being so quick on this.
