### ISSUE TITLE
Support for `pg_ivm`

### ISSUE THREAD

**Issue by radusuciu** [xelixdev/django-pgviews-redux#33]
Are there any plans for supporting creating materialized views using the [`pg_ivm`](https://github.com/sraoss/pg_ivm) extension?

Thanks for maintaining this extension!

**Comment by mikicz** [comment]
Hi @radusuciu - there's not immediate plans, but I am happy to work with you on adding this in a PR, if really need this feature

**Comment by radusuciu** [comment]
It's not essential to me right now because the extension still has some limitations that mean I can't use it for most things. However, if those limitations are removed, or if my use case changes, I may be motivated enough to submit a PR. Thank you for the response!
