### ISSUE TITLE
Decouple post_migrate signal from refreshing the views

### ISSUE THREAD

**Issue by sidmitra** [xelixdev/django-pgviews-redux#76]
**Problem**

Currently the post_migrate signal triggers automatic `sync_pgviews()` in the AppConfig.ready()

See [here](https://github.com/xelixdev/django-pgviews-redux/blob/c9b9b6da882de3f7a672ef6a23d3d6c4b8c5f1bb/django_pgviews/apps.py#L47)

```
def ready(self):
        """
        Find and setup the apps to set the post_migrate hooks for.
        """
        signals.post_migrate.connect(self.sync_pgviews)
```

While this is fine for most use-cases, this becomes an issue as the number and size of the pgviews grow. At that point it slows down deploys and if a refresh timesout it fails a deploy.  For some teams/orgs making the refresh async is an OK tradeoff. Thus we'd want this coupling to be optional.

**Solution**
Make the current behaviour the default, but add an environment variable or django settings config to override and decouple this. i.e. optionally decide to not connect sync_pgviews to post_migrate signal. 

---

If this makes sense i can send a PR.

**Comment by mikicz** [comment]
Yep definitely that makes sense - as long as current default remains default. If you submit a PR I'll happily merge and release

**Comment by sidmitra** [comment]
@mikicz Thanks for the quick reply. Will send a PR.

**Comment by themrinalsinha** [comment]
Submitted a PR to resolve this: https://github.com/xelixdev/django-pgviews-redux/pull/77
